<!-- My Conversations Section -->
<!-- <p>The My Conversations section is designed to support employees and supervisors to have the right conversation at the right time. Visit the <a href='/resource/conversations' target=\'_blank\'>Performance Conversations</a> resource for more information on best practices.</p> -->
<p>The My Conversations section is designed to support employees and supervisors to have the right conversation at the right time.</p>
<!-- <p>Every employee must record at least one performance conversation every four months (three per year). However, the topic and nature of each performance conversation does not have to be the same. The PDP has templates to support conversations focused on onboarding a new employee, goal setting, performance check-ins, performance improvement, and career development. Each of these count as a performance conversation. Check out the resource on <a href='/resource/conversations?t=5' target=\'_blank\'>Performance Conversation Templates</a> to see all the options and suggestions for when to use each one.</p> -->
<p>Every employee must record at least one performance conversation every four months (three per year). However, the topic and nature of each performance conversation does not have to be the same. The PDP has templates to support conversations focused on onboarding a new employee, goal setting, performance check-ins, career development, and performance improvement. Each of these count as a performance conversation. Check out the resource on <a href='/resources/conversations?t=5' target=\'_blank\'>Performance Conversation Templates</a> to see all the options and suggestions for when to use each one.</p>
<p>Furthermore, each employee has their own unique performance conversation deadline in the PDP. Not all conversations happen across the organization at the same time. Once you complete a performance conversation, your personal deadline becomes the date you completed the conversation plus four months. For example, if my supervisor and I sign-off on a performance check-in conversation on February 10, my next conversation will be due on June 10 (Feb 10 plus four months). This provides greater flexibility for when performance conversations occur.</p>
<br>
<u>Conversation Templates</u>
<br><br>
<!-- <p>This area lists all the performance conversation templates available for use. Each templates includes suggestions for when to use it, tips on how employees and supervisors can prepare for the conversation, and a list of questions to consider in advance or during the conversation to guide discussion. You may also want to check out the resource on <a href='/resource/conversations?t=5' target=\'_blank\'>Performance Conversation Templates</a> to see more details on all the options and examples for when to use each one.</p> -->
<p>This area lists all the performance conversation templates available for use. Each templates includes suggestions for when to use it, tips on how employees and supervisors can prepare for the conversation, and a list of questions to consider in advance or during the conversation to guide discussion. You may also want to check out the resource on <a href='/resources/conversations' target=\'_blank\'>Performance Conversation Templates</a> to see more details on all the options and examples for when to use each one.</p>
<p>Once you've decided on the right template, use the participants dropdown menu to select which team member or supervisor you want to connect with and hit "Start Conversation" to alert them that you want to meet. An email will be sent but conversations will still need to be scheduled independently in your Outlook calendar.</p>
<br>

<u>Open Conversations</u>
<br><br>
<p>This area lists all planned or in progress conversations that have yet to be signed-off by both employee and supervisor. Each open conversations includes an optional list of questions to help guide the conversation, text boxes to capture major conversation outcomes, and an attestation and sign-off area to formalize the results.</p>
<p>Note that as soon as either employee or supervisor signs off on the open conversation, the content is locked and no additional comments can be made. Both participants should add all comments before either sign.</p>
<p>Once a conversation has been signed-off by both participants, it moves to the Completed Conversations tab and becomes an official performance development record for the employee. Their next performance conversation deadline will be set for the sign-off date plus four months.</p>
<br>

<u>Completed Conversations</u>
<br><br>
<p>This area contains all conversations that have been signed by both employee and supervisor. There is a two-week period from the date of sign-off when either participant can un-sign the conversation to return it to the Open Conversations tab for further edits. Conversations that have passed the two-week period require approval and assistance to re-open. If you need to unlock a conversation, submit an <a target="blank" href="https://www2.gov.bc.ca/gov/content/careers-myhr">AskMyHR</a> service request to Myself > HR Software Systems Support > Performance Development Platform.</p>
    